server:
  port: 8081

spring:
  application:
    name: btg-fondos-api
  main:
    banner-mode: console

# AWS
aws:
  region: ${AWS_REGION:us-east-1}
  dynamodb:
    endpoint: ${AWS_DYNAMODB_ENDPOINT:}

# JWT
app:
  jwt:
    secret: ${APP_JWT_SECRET:DefaultDevSecretKeyMustBeAtLeast32CharsLong!!}
    expiration-ms: ${APP_JWT_EXPIRATION:86400000}
  notification:
    sender-email: ${APP_SENDER_EMAIL:spenilla2@gmail.com}

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized
  info:
    env:
      enabled: true

info:
  app:
    name: BTG Pactual - Fondos API
    version: 1.0.0
    description: API REST para gestion de fondos de inversion

# Swagger
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
